AWSTemplateFormatVersion: "2010-09-09"
Description: Chatbot Feed Notifications
Parameters:
  FeedUrl:
    Type: String
    Description: The URL of the feed to publish
  NotificationsTopicArn:
    Type: String
    Description: ARN of the SNS topic to send Chatbot notifications

Resources:
  LatestPublishedParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: LatestPublishedTimestamp
      Type: String
      Value: '0'
      Description: Timestamp of the latest published feed entry

  FeedNotificationsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FeedNotificationsExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: PublishNotificationToSns
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref NotificationsTopicArn
        - PolicyName: LatestPublishedParameterReadWrite
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:PutParameter
                Resource:
                  - !Sub
                    - 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ParameterName}'
                    - ParameterName: !Ref LatestPublishedParameter


  FeedNotificationsDependenciesLambdaLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      #LayerName: 'FeedNotificationsDependencies'
      CompatibleRuntimes:
        - 'python3.10'
      CompatibleArchitectures:
        - x86_64
      Content:
        S3Bucket: lambda-function-examples
        S3Key: feed_notifications-dependencies.zip

  FeedNotificationsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Role: !GetAtt FeedNotificationsExecutionRole.Arn
      Timeout: 30
      Environment:
        Variables:
          FEED_URL: !Ref FeedUrl
          SNS_TOPIC_ARN: !Ref NotificationsTopicArn
          SSM_PARAM_LATEST_ENTRY: !Ref LatestPublishedParameter
      Code:
        S3Bucket: lambda-function-examples
        S3Key: feed_notifications.zip
      Layers:
        - !Ref FeedNotificationsDependenciesLambdaLayer

  CheckFeedRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Trigger FeedNotifications"
      ScheduleExpression: "rate(10 minutes)"
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt FeedNotificationsFunction.Arn
          Id: "RunFeedNotifications" 

  InvokeFeedNotificationsFunctionPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt FeedNotificationsFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CheckFeedRule.Arn